name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build_test_deploy:
    name: "Build, Test & Deploy"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build the docker image
        run: docker-compose build

      - name: Run the tests
        run: docker-compose run alwaysontime pipenv run pytest

      - name: Write docker certificates locally
        run: |
          mkdir ./docker_certs
          echo "${{ secrets.DOCKER_CERT_CA_PEM }}" > ./docker_certs/ca.pem
          echo "${{ secrets.DOCKER_CERT_CERT_PEM }}" > ./docker_certs/cert.pem
          echo "${{ secrets.DOCKER_CERT_KEY_PEM }}" > ./docker_certs/key.pem

      - name: Deploy to 'floriankempenich.com:8000'
        run: |
          export DOCKER_TLS_VERIFY="1"
          export DOCKER_HOST="tcp://floriankempenich.com:2376"
          export DOCKER_CERT_PATH="$PWD/docker_certs"
          
          docker-compose up --build -d

      - name: Migrate the DB
        run: |
          export DOCKER_TLS_VERIFY="1"
          export DOCKER_HOST="tcp://floriankempenich.com:2376"
          export DOCKER_CERT_PATH="$PWD/docker_certs"
          
          docker-compose run alwaysontime pipenv run python manage.py migrate

      - name: Cleanup docker certificates
        if: always()
        run: rm -rf ./docker_certs
          
